import Head from "next/head";

export const metadata = {
    title: 'Ldtax Portal',
    description: 'Generated by create next app',
    charSet: "UTF-8",
    httpEquiv:"X-UA-Compatible",
    content:"IE=edge",
    name:"viewport", 
    content:"width=device-width, initial-scale=1.0"
}

export default function Header  ()  {
    
    return  (
        <div className="headersec">hello</div>
    )
}


